/**
 * Host-game compatibility for the canonical Blender Mustang adapter.
 * The asset owns its visual rig; the host still owns flight and crash physics.
 * Assembly containers are IDENTITY children of visualRoot: moving an authored
 * scene-root node into one never changes the coordinates expected by its clips.
 */
import * as THREE from 'three';
import {
  loadPlane as loadAsset,
  updatePlaneVisual as updateAssetVisual,
} from '../assets/mustang/mustang.js';
export { aircraftInfo, aircraftCapabilities, disposePlane } from '../assets/mustang/mustang.js';

const ASSEMBLIES = {
  fuselage: { name: 'Mustang fuselage and cockpit' },
  wingPort: { name: 'Mustang port wing assembly', strength: 15 },
  wingStarboard: { name: 'Mustang starboard wing assembly', strength: 21 },
  stabilizerPort: { name: 'Mustang port stabilizer and elevator', strength: 34 },
  stabilizerStarboard: { name: 'Mustang starboard stabilizer and elevator', strength: 34 },
  fin: { name: 'Mustang fin and rudder', strength: 26 },
  propeller: { name: 'Mustang propeller assembly', strength: 7, collision: false },
  tailGear: { name: 'Mustang tailwheel assembly', strength: 19 },
};

// The authored whole-airframe aft extension also stretches the tail tyre/hub
// along Z: its rolling section becomes 318 x 331.395mm instead of circular.
// Spinning that ellipse causes up to 6.7mm ground penetration. Compensate ONLY
// those two spinning geometries in the host copy, around their actual spindle.
// The canonical GLB, rig, node transforms, axle position and materials remain
// unchanged. applyMatrix4 also applies the proper inverse-transpose to normals.
function normalizeTailwheelRollingGeometry(plane) {
  const wheel = plane.tailWheelSpin;
  if (!wheel) throw new Error('Mustang tailwheel spindle is missing.');
  plane.group.updateMatrixWorld(true);
  const inverse = wheel.matrixWorld.clone().invert(), point = new THREE.Vector3();
  const owners = [], tireBox = new THREE.Box3();
  wheel.traverse(node => {
    if (!node.isMesh || !['tail-tire', 'tail-cast-hub'].includes(ancestorData(node, 'detail_role'))) return;
    const toSpindle = new THREE.Matrix4().multiplyMatrices(inverse, node.matrixWorld);
    owners.push({ node, toSpindle });
    if (ancestorData(node, 'detail_role') === 'tail-tire') {
      for (let i = 0; i < node.geometry.attributes.position.count; i++) {
        node.getVertexPosition(i, point).applyMatrix4(toSpindle);
        tireBox.expandByPoint(point);
      }
    }
  });
  if (tireBox.isEmpty() || !owners.some(({ node }) => ancestorData(node, 'detail_role') === 'tail-cast-hub'))
    throw new Error('Mustang tailwheel rolling geometry is incomplete.');
  const diameters = tireBox.getSize(new THREE.Vector3());
  const radialZScale = diameters.y / diameters.z;
  if (!(radialZScale > .9 && radialZScale < 1.1)) throw new Error('Unexpected Mustang tailwheel rolling proportions.');
  const scale = new THREE.Matrix4().makeScale(1, 1, radialZScale), corrected = [];
  for (const { node, toSpindle } of owners) {
    const correction = toSpindle.clone().invert().multiply(scale).multiply(toSpindle);
    node.geometry = node.geometry.clone().applyMatrix4(correction);
    node.userData.gameGeometryCorrection = 'tailwheel-aft-stretch-compensation';
    corrected.push({ name: node.name, role: ancestorData(node, 'detail_role'), matrix: correction.toArray() });
  }
  plane.integrationCorrections = { tailwheelRollingGeometry: {
    reason: 'Compensate authored aft-datum Z stretch of rotating tyre and hub only',
    canonicalAssetUnchanged: true, sourceDiameterY: diameters.y, sourceDiameterZ: diameters.z,
    radialZScale, frame: 'wheel_tail spindle local', corrected,
  } };
}

// Most structural owners are declared in source extras. Fixed tail surfaces
// do not have semantic role tags, so use their original GLB names (not the
// sanitized names generated by GLTFLoader) for those two explicit fallbacks.
function sourceName(plane, node) {
  const index = plane.gltf.parser.associations.get(node)?.nodes;
  return plane.gltf.parser.json.nodes[index]?.name || node.userData.name || node.name;
}

function assemblyFor(plane, node) {
  const data = node.userData, id = data.control_id || '';
  const name = sourceName(plane, node);
  if (id === 'propeller_spin' || data.propeller_animation_version) return 'propeller';
  if (id === 'gear_tail' || data.detail_role === 'tail-steering-link' ||
      name.startsWith('RIG | Tail steering link fixed anchor')) return 'tailGear';
  if (id === 'rudder' || data.tail_geometry_revision) return 'fin';
  for (const [side, suffix] of [['port', 'Port'], ['starboard', 'Starboard']]) {
    if (id === `elevator_${side}` || name === `P51D | ${side} continuous horizontal tail`)
      return `stabilizer${suffix}`;
    if (data.wing_flex_side === side || data.control_flex_side === side ||
        id === `gear_${side}` || id === `gear_door_main-trunnion_${side}` ||
        (data.assembly_side === side && ['main-retract-cylinder', 'main-retract-rod', 'main-trunnion'].includes(data.detail_role)))
      return `wing${suffix}`;
  }
  // Fixed wing-root fillets, belly-mounted inner doors, and fixed tail bearing
  // carriers remain on the fuselage when their adjoining assembly shears.
  return 'fuselage';
}

function installAssemblies(plane) {
  const originals = [...plane.visualRoot.children];
  const semanticParts = {};
  for (const [id, definition] of Object.entries(ASSEMBLIES)) {
    const object = new THREE.Group();
    object.name = definition.name;
    object.userData.gameAssembly = id;
    plane.visualRoot.add(object);
    semanticParts[id] = object;
  }
  for (const node of originals) semanticParts[assemblyFor(plane, node)].add(node);
  for (const [id, object] of Object.entries(semanticParts)) {
    if (!object.children.length) throw new Error(`Mustang compatibility assembly is empty: ${id}`);
  }
  plane.semanticParts = semanticParts;
  plane.breakawayParts = Object.entries(semanticParts)
    .filter(([id]) => Number.isFinite(ASSEMBLIES[id].strength))
    .map(([id, object]) => ({ object, strength: ASSEMBLIES[id].strength }));
  plane.group.updateMatrixWorld(true);
}

function installCollisionParts(plane) {
  const originals = [...new Set(plane.nodes.values())];
  const find = name => originals.find(node => sourceName(plane, node) === name);
  const monocoque = find('Airframe | continuous Mustang monocoque with sealed cockpit recess');
  const windscreen = find('Cockpit | closed armoured windscreen with quarter panes');
  const radiator = find('Cooling | closed radiator fairing and recessed dark core');
  if (!monocoque || !windscreen || !radiator) throw new Error('Mustang structural collision owners are missing.');
  // The semantic fuselage ALSO owns small fittings and open belly gear doors.
  // Their union badly inflates a full-length capsule (up to 2.5m wide), so the
  // collision hull contains ONLY the monocoque; glazing and cooler are separate
  // short boxes. Keep the host's existing name-based fuselage capsule dispatch.
  const hull = new THREE.Group();
  hull.name = 'Mustang fuselage shell';
  hull.userData.gameCollisionRole = 'fuselage';
  plane.semanticParts.fuselage.add(hull);
  hull.add(monocoque); // Both old and new parents are identity local frames.
  plane.collisionParts = [hull, plane.canopy, windscreen, radiator, plane.radiatorDoor,
    ...Object.entries(plane.semanticParts)
      .filter(([id]) => id !== 'fuselage' && ASSEMBLIES[id].collision !== false)
      .map(([, object]) => object)];
  plane.group.updateMatrixWorld(true);
}

function ancestorData(node, key) {
  for (let owner = node; owner; owner = owner.parent) {
    if (owner.userData[key] !== undefined) return owner.userData[key];
  }
}

// Measure actual neutral vertices, avoiding bounding boxes expanded by every
// possible morph target. Measurements are always in the host physics frame.
function geometryBounds(plane, objects) {
  plane.group.updateMatrixWorld(true);
  const inverse = plane.group.matrixWorld.clone().invert();
  const matrix = new THREE.Matrix4(), point = new THREE.Vector3(), box = new THREE.Box3();
  for (const object of objects) object.traverse(node => {
    if (!node.isMesh || !node.geometry?.attributes.position) return;
    matrix.multiplyMatrices(inverse, node.matrixWorld);
    for (let i = 0; i < node.geometry.attributes.position.count; i++) {
      node.getVertexPosition(i, point).applyMatrix4(matrix);
      box.expandByPoint(point);
    }
  });
  if (box.isEmpty()) throw new Error('Mustang ground-contact geometry is missing.');
  return box;
}

// A tilted round tyre contacts a different point than its neutral bottom.
// Retain a small set of REAL tyre vertices which supports the attitude range
// used by ground physics; no collision mesh or hand-entered radius is needed.
// Sampling up directions every .02 radians is appreciably finer than these
// tyres' authored circumference and rounded-sidewall tessellation.
function tireSupportPoints(plane, objects) {
  const inverse = plane.group.matrixWorld.clone().invert();
  const matrix = new THREE.Matrix4(), point = new THREE.Vector3(), unique = new Map();
  for (const object of objects) object.traverse(node => {
    if (!node.isMesh || !node.geometry?.attributes.position) return;
    matrix.multiplyMatrices(inverse, node.matrixWorld);
    for (let i = 0; i < node.geometry.attributes.position.count; i++) {
      node.getVertexPosition(i, point).applyMatrix4(matrix);
      const xyz = point.toArray();
      unique.set(xyz.map(value => value.toFixed(7)).join(','), xyz);
    }
  });
  const vertices = [...unique.values()], retained = new Set();
  for (let pitchIndex = 0; pitchIndex <= 35; pitchIndex++) {
    const pitch = -.20 + pitchIndex * .02;
    for (let bankIndex = 0; bankIndex <= 35; bankIndex++) {
      const bank = -.35 + bankIndex * .02;
      const x = Math.sin(bank) * Math.cos(pitch), y = Math.cos(bank) * Math.cos(pitch), z = -Math.sin(pitch);
      let lowest = Infinity, winner = 0;
      for (let i = 0; i < vertices.length; i++) {
        const vertex = vertices[i], height = vertex[0] * x + vertex[1] * y + vertex[2] * z;
        if (height < lowest) { lowest = height; winner = i; }
      }
      retained.add(winner);
    }
  }
  if (!vertices.length) throw new Error('Mustang tyre support geometry is missing.');
  return [...retained].map(index => vertices[index]);
}

function measureGroundContact(plane) {
  const tires = { port: [], starboard: [], tail: [] }, belly = [];
  plane.group.traverse(node => {
    const role = node.userData.detail_role;
    if (role === 'main-tire') tires[node.userData.assembly_side]?.push(node);
    if (role === 'tail-tire') tires.tail.push(node);
    const name = sourceName(plane, node);
    if (name === 'Airframe | continuous Mustang monocoque with sealed cockpit recess' ||
        name === 'Cooling | closed radiator fairing and recessed dark core' ||
        node.userData.control_pivot && node.userData.control_id === 'radiator') belly.push(node);
  });
  const bottom = objects => {
    const box = geometryBounds(plane, objects), center = box.getCenter(new THREE.Vector3());
    return [center.x, box.min.y, center.z];
  };
  const mainPort = bottom(tires.port), mainStarboard = bottom(tires.starboard);
  return {
    main: [...mainStarboard],
    mainHalfTrack: Math.abs(mainStarboard[0] - mainPort[0]) * 0.5,
    tail: bottom(tires.tail),
    mainPort, mainStarboard,
    bellyHeight: -geometryBounds(plane, belly).min.y,
    supportPoints: {
      mainPort: tireSupportPoints(plane, tires.port),
      mainStarboard: tireSupportPoints(plane, tires.starboard),
      tail: tireSupportPoints(plane, tires.tail),
    },
    supportPitchRange: [-.20, .50], supportBankRange: [-.35, .35],
    units: 'metres', frame: 'plane.group', pose: 'neutral gear down',
  };
}

function installTipMarker(plane, side, parent) {
  const meshes = plane.flexMeshes.filter(({ node, side: flexSide }) =>
    flexSide === side && ancestorData(node, 'wing_flex_role') === 'main wing closed shell');
  if (!meshes.length) throw new Error(`Missing ${side} wing-tip geometry.`);
  const inverse = parent.matrixWorld.clone().invert();
  const matrix = new THREE.Matrix4(), point = new THREE.Vector3();
  let extreme = -Infinity;
  for (const { node } of meshes) {
    matrix.multiplyMatrices(inverse, node.matrixWorld);
    for (let i = 0; i < node.geometry.attributes.position.count; i++) {
      node.getVertexPosition(i, point).applyMatrix4(matrix);
      extreme = Math.max(extreme, Math.abs(point.x));
    }
  }
  // Average the terminal skin ring. Store its actual vertex indices, not a
  // second approximation of the bend field, so Up/Down and asymmetric gusts
  // follow precisely the same morph interpolation as the visible wing.
  const samples = [];
  for (const { node } of meshes) {
    matrix.multiplyMatrices(inverse, node.matrixWorld);
    for (let i = 0; i < node.geometry.attributes.position.count; i++) {
      node.getVertexPosition(i, point).applyMatrix4(matrix);
      if (Math.abs(point.x) >= extreme - 0.001) samples.push({ node, index: i });
    }
  }
  const marker = new THREE.Object3D();
  marker.name = `Mustang ${side} wing-tip trail origin`;
  parent.add(marker);
  return { marker, samples, inverse, matrix, point, sum: new THREE.Vector3() };
}

function updateTips(plane) {
  for (const binding of plane.tipBindings) {
    const { marker, samples, inverse, point, sum } = binding;
    inverse.copy(marker.parent.matrixWorld).invert();
    sum.set(0, 0, 0);
    for (const { node, index } of samples) {
      node.getVertexPosition(index, point).applyMatrix4(node.matrixWorld).applyMatrix4(inverse);
      sum.add(point);
    }
    marker.position.copy(sum).divideScalar(samples.length);
    marker.updateMatrixWorld(true);
  }
}

export async function loadPlane(
  url = new URL('../assets/mustang/P51D_Mustang.glb', import.meta.url), onProgress,
) {
  const plane = await loadAsset(url, onProgress);
  normalizeTailwheelRollingGeometry(plane);
  installAssemblies(plane);
  installCollisionParts(plane);
  // Capture contact geometry before the game-specific visual-life defaults
  // are enabled; stance must never depend on vibration phase or wing gusts.
  plane.groundContact = measureGroundContact(plane);
  plane.tipBindings = [
    installTipMarker(plane, 'port', plane.semanticParts.wingPort),
    installTipMarker(plane, 'starboard', plane.semanticParts.wingStarboard),
  ];
  [plane.tipL, plane.tipR] = plane.tipBindings.map(binding => binding.marker);
  Object.assign(plane.state, { flightMotion: 1, engineVibration: 0.55, turbulence: 0.25, controlVibration: 0.4 });
  plane.integrationVersion = 'mustang-host-game/1';
  updatePlaneVisual(plane, {}, {}, 0);
  return plane;
}

export function updatePlaneVisual(plane, input = {}, physics = {}, dt = 0) {
  // Crash debris reparents these semantic groups into independent rigid
  // bodies. Freeze the complete authored pose: mixer, morphs, steering rods,
  // propeller and shake must not rewrite any detached part's local transform.
  // Once wreckage.restore() reattaches them, an uncrashed update resumes the
  // normal rig and restores its visualRoot from the canonical rest transform.
  if (physics.crashed) return plane;
  updateAssetVisual(plane, input, physics, dt);
  updateTips(plane);
  return plane;
}
